#!/usr/bin/env -S just --justfile

##
# Justfile (like Makefile) - make it easier and faster to use maven ->
# https://just.systems/

set shell := ["bash", "-cu"]

cli:
	java -jar target/async-data-fetcher-0.0.1-SNAPSHOT.jar cli

serve:
	java -jar target/async-data-fetcher-0.0.1-SNAPSHOT.jar

clean:
    ./mvnw clean

distclean:
	rm -rf target

compile:
    ./mvnw compile

build-only:
    ./mvnw clean package -DskipTests -Dmaven.test.skip=true

build:
    ./mvnw clean package

build-and-test:
    ./mvnw clean package

test-only:
    ./mvnw test

test:
    ./mvnw test

########################

profile:
    ./mvnw exec:exec -Dexec.executable="jvisualvm"

heapdump:
    jcmd $(pgrep -f 'java.*MyApp') GC.heap_dump target/heapdump.hprof

thread-dump:
    jcmd $(pgrep -f 'java.*MyApp') Thread.print > target/threaddump.txt

gdb-java:
    gdb --args java -jar target/*.jar

debug:
    mvnDebug spring-boot:run



####


perf-test-jmeter:
    jmeter -n -t perf-tests/script.jmx -l perf-tests/results.jtl -e -o perf-tests/report

stress-test:
    k6 run --vus 500 --duration 2m perf-tests/script.js

load-test:
    k6 run --vus 100 --duration 10m perf-tests/script.js

soak-test:
    k6 run --vus 50 --duration 24h perf-tests/script.js
