#!/usr/bin/env -S just --justfile

default: cli

cli:
	./gradlew bootRun --args="cli"

serve:
	./gradlew bootRun

build:
	./gradlew build

test:
	./gradlew test

build-all:
	./gradlew clean build

build-only:
	./gradlew assemble

test-only:
	./gradlew test

clean:
	./gradlew clean
