#!/usr/bin/env -S just --justfile

default: build

build:
	@echo "Building the project for wasm32-unknown-unknown with wrangler..."
	wrangler deploy --dry-run --outdir=dist

cargo-build:
    @echo "Building the project for wasm32-unknown-unknown..."
    cargo build --lib --release --target wasm32-unknown-unknown

clean:
    @echo "Cleaning project..."
    cargo clean

fmt:
    @echo "Formatting code..."
    cargo fmt

clippy:
    @echo "Running clippy..."
    cargo clippy --all-targets --all-features -- -D warnings

test:
    @echo "Running tests..."
    cargo test

dev:
    @echo "Starting Wrangler dev server..."
    wrangler dev

deploy:
    @echo "Deploying to Cloudflare Workers..."
    wrangler deploy
